/**
 * ADR-005 section 2: harness-run classification and the minimal attribution
 * of temp-cwd sessions to the launched repo. Fixtures: the Claude harness and
 * temp-copy sessions from test/fixtures/claude/make-fixtures.mjs, parsed by the
 * real adapter, indexed with the real `buildEntry`, and matched against a
 * temporary repo whose files and instruction chain the test writes.
 */
import assert from "node:assert/strict";
import { test } from "node:test";
import os from "node:os";
import path from "node:path";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { parseClaudeSession } from "../src/adapters/claude.mjs";
import { buildEntry, habitsOf, isRepoRelativeTarget, nestedHashesOf, sessionKindOf, targetsOf } from "../src/index/entry.mjs";
import { attributionOf, cwdKindOf, entryUnattributed, repoSessions, sessionKindOfEntry } from "../src/index/reader.mjs";
import { buildOverviewFromEntries } from "../src/index/overview.mjs";
import { collectInstructionFiles } from "../src/setup/instructions.mjs";
import { evaluateHabitsDetailed } from "../src/rules/habits.mjs";
import { projectKeyFor } from "../src/ir/project.mjs";
import { DIR, HARNESS_CWD, HOME, NESTED_MEMORY_PATH, NESTED_MEMORY_TEXT, SESSIONS, TEMP_COPY_CWD, TEMP_TARGETS } from "./fixtures/claude/make-fixtures.mjs";

// The fixture files are committed and regenerated by adapter-claude.test.mjs; this file only reads them (no concurrent rewrite).
const NOW = Date.parse("2026-09-02T12:00:00Z");
const sha1 = (text) => createHash("sha1").update(text).digest("hex");
const file = (id) => path.join(DIR, `${id}.jsonl`);

async function entryFor(id) {
  const run = await parseClaudeSession(file(id), { home: HOME });
  // The discovery candidate carries the cwd read from the transcript head; the fixture sessions declare it on every record.
  const cwd = id === SESSIONS.harness ? HARNESS_CWD : id === SESSIONS.tempCopy ? TEMP_COPY_CWD : `${HOME}/projects/lorem`;
  const candidate = { size: 1, mtimeMs: 1, cwd, projectKey: run.project.key, projectDisplay: run.project.displayName };
  return { run, entry: buildEntry({ run, findings: [], candidate, adapterVersion: "claude-test", thresholdsHash: "t", file: `~/x/${id}.jsonl`, thresholds: {} }) };
}

/** Manifest-shaped entry for population tests (mirrors overview-scope.test.mjs). */
function fakeEntry(id, { vendor = "claude", cwd, kind, entrypoint, requests = 10, toolCalls = 1, targets = [], nestedHashes = [], instructionHash, endedAt = "2026-09-01T10:00:00Z" } = {}) {
  const key = cwd ? projectKeyFor(cwd) : `enc-${id}`;
  const summary = { requests, turns: 1, processedInputTokens: requests * 1000, outputTokens: 10, cacheReadShare: 0.5, peak: { value: 50_000, provenance: "observed.vendor" }, peakShareOfWindow: 0.25, compactions: 0, subagents: 0, toolCalls, models: ["m"], topBlocks: [], findingIds: [] };
  const cwdKind = cwdKindOf(cwd ?? null);
  return {
    vendor, runId: `${vendor}:${id}`, sessionId: id, file: `~/x/${id}.jsonl`, projectKey: key, discoveryKey: key, projectDisplay: cwd ? path.basename(cwd) : "unknown",
    project: { key, displayName: cwd ? path.basename(cwd) : "unknown", cwdHash: "h" }, cwd: cwd ?? null, cwdKind, cwdReversible: Boolean(cwd),
    entrypoint, kind: kind ?? sessionKindOf({ entrypoint, cwdKind, summary }), targets, nestedHashes, ...(instructionHash ? { instructionHash } : {}),
    startedAt: endedAt, endedAt, activeMs: 1000, window: { value: 200_000, provenance: "estimated.local" }, summary,
    findingsCount: 0, findingsHigh: 0, findingHeads: [], handoffs: [], stats: { sessionCount: 1, vendorsWithSessions: [vendor] },
    habits: { v: 3, fat: [{ tool: "Read", kind: "file", label: "src/index.mjs", tokens: 12_000, n: 1 }], fullReads: [], agents: [], compaction: { n: 0, auto: 0, requests }, startup: { h0: 12_000 }, mcp: { invoked: [] }, peakShare: 0.25, window: 200_000 },
  };
}

test("entry fields: kind, entrypoint, targets (repo-relative only, deduplicated), nestedHashes; the harness fixture is a harness run", async () => {
  const { run, entry } = await entryFor(SESSIONS.harness);
  assert.equal(run.entrypoint, "sdk-cli");
  assert.equal(entry.entrypoint, "sdk-cli");
  assert.equal(entry.cwdKind, "temp");
  assert.equal(entry.kind, "harness");
  assert.equal(entry.summary.toolCalls, 0);
  assert.equal(entry.summary.requests, 1);
  assert.deepEqual(entry.targets, []);
  assert.deepEqual(entry.nestedHashes, []);
  assert.equal(entry.instructionHash, undefined, "instructionHash is Codex-only");

  const temp = await entryFor(SESSIONS.tempCopy);
  assert.equal(temp.entry.kind, "interactive", "a temp-cwd session with tool calls is never a harness run");
  assert.equal(temp.entry.entrypoint, "cli");
  assert.deepEqual(temp.entry.targets, TEMP_TARGETS, "six distinct repo-relative targets, the Bash `cat` included, in order of appearance");
  for (const target of temp.entry.targets) assert.ok(isRepoRelativeTarget(target) && !target.startsWith("/") && !target.startsWith("~"), target);
  assert.equal(temp.entry.nestedHashes.length, 1);
  assert.equal(temp.entry.nestedHashes[0], sha1(NESTED_MEMORY_TEXT).slice(0, 16), "the nested_memory block hash is the hash of the file content");
  assert.ok(!JSON.stringify({ ...temp.entry, cwd: null }).includes(TEMP_COPY_CWD), "no absolute path in the entry besides `cwd` (the manifest contract)");
  assert.ok(!JSON.stringify(temp.entry.targets).includes("/private/"));

  // Classification rule, directly.
  assert.equal(sessionKindOf({ entrypoint: "sdk-cli", cwdKind: "repo", summary: { toolCalls: 30, requests: 40 } }), "harness", "an SDK entrypoint is a harness run whatever it did");
  assert.equal(sessionKindOf({ entrypoint: "cli", cwdKind: "temp", summary: { toolCalls: 0, requests: 2 } }), "harness");
  assert.equal(sessionKindOf({ entrypoint: "cli", cwdKind: "temp", summary: { toolCalls: 0, requests: 3 } }), "interactive");
  assert.equal(sessionKindOf({ entrypoint: "cli", cwdKind: "temp", summary: { toolCalls: 1, requests: 1 } }), "interactive");
  assert.equal(sessionKindOf({ entrypoint: "cli", cwdKind: "repo", summary: { toolCalls: 0, requests: 1 } }), "interactive", "a one-request session in a real repo is a session");
  assert.equal(sessionKindOfEntry({ kind: undefined }), "interactive", "entries indexed before the field are interactive");

  // Bounded, relative-only helpers over a synthetic run.
  const synthetic = { scopes: [{ kind: "main", blocks: [
    { category: "tool_call", tool: { name: "Read", kind: "file", argsHash: "a", target: "/abs/x.ts" } },
    { category: "tool_call", tool: { name: "Read", kind: "file", argsHash: "b", target: "~/.zshrc" } },
    { category: "tool_call", tool: { name: "Bash", kind: "file", argsHash: "c", target: "../up.ts" } },
    { category: "tool_call", tool: { name: "Bash", kind: "search", argsHash: "d", target: "." } },
    ...Array.from({ length: 40 }, (_, i) => ({ category: "tool_call", tool: { name: "Read", kind: "file", argsHash: `r${i}`, target: `src/f${i}.ts` } })),
    { category: "attachments", attachmentType: "nested_memory", label: "packages/x/CLAUDE.md", hash: "f".repeat(40) },
    { category: "attachments", attachmentType: "nested_memory", label: "skill", hash: "e".repeat(40) },
  ] }] };
  const targets = targetsOf(synthetic);
  assert.equal(targets.length, 32, "at most 32 targets");
  assert.ok(targets.every((target) => target.startsWith("src/")), "absolute, ~-relative, parent and `.` targets are dropped");
  assert.deepEqual(nestedHashesOf(synthetic), ["f".repeat(16)], "only instruction-file labels, truncated to 16 hex");
});

test("attribution: nested-hash and path-overlap fire against a real repo inventory and file list; two targets do not; never for a repo cwd or a harness run", async () => {
  const base = await mkdtemp(path.join(os.tmpdir(), "contextscope-attr-"));
  try {
    const repo = path.join(base, "repo");
    const home = path.join(base, "home");
    await mkdir(home, { recursive: true });
    for (const target of TEMP_TARGETS) { await mkdir(path.dirname(path.join(repo, target)), { recursive: true }); await writeFile(path.join(repo, target), `// ${target}\n`); }
    await writeFile(path.join(repo, "CLAUDE.md"), "# Repo\n\nRoot instructions.\n");
    await writeFile(path.join(repo, NESTED_MEMORY_PATH), NESTED_MEMORY_TEXT);
    const inventory = await collectInstructionFiles({ repoRoot: repo, home, vendorsDetected: ["claude"], sessionStats: null, captureObserved: [] });
    const nested = inventory.files.find((f) => f.path === NESTED_MEMORY_PATH);
    assert.ok(nested, "the nested file is in the chain");
    assert.equal(nested.hash, sha1(NESTED_MEMORY_TEXT), "InstructionFile.hash is the sha1 of the content");
    assert.ok(inventory.files.every((f) => /^[0-9a-f]{40}$/.test(f.hash)));
    const chainHashes = inventory.files.map((f) => f.hash);
    const repoFiles = new Set([...TEMP_TARGETS, "CLAUDE.md", NESTED_MEMORY_PATH]);
    const key = projectKeyFor(repo);

    const { entry } = await entryFor(SESSIONS.tempCopy);

    // Priority: nested-hash (exact) before path-overlap (derived).
    assert.deepEqual(attributionOf(entry, { repoRoot: repo, repoFiles, chainHashes }), { key, method: "nested-hash", confidence: "exact" });
    // Without the chain: six targets, all in the repo -> path overlap with the matched count.
    assert.deepEqual(attributionOf(entry, { repoRoot: repo, repoFiles }), { key, method: "path-overlap", confidence: "derived", files: 6 });
    // 5 of 6 present (83 %) still passes; 4 of 6 (67 %) does not; two targets never do.
    assert.equal(attributionOf(entry, { repoRoot: repo, repoFiles: new Set(TEMP_TARGETS.slice(0, 5)) })?.method, "path-overlap");
    assert.equal(attributionOf(entry, { repoRoot: repo, repoFiles: new Set(TEMP_TARGETS.slice(0, 4)) }), null);
    assert.equal(attributionOf({ ...entry, targets: TEMP_TARGETS.slice(0, 2) }, { repoRoot: repo, repoFiles }), null, "two targets are not enough");
    assert.equal(attributionOf({ ...entry, targets: [] }, { repoRoot: repo, repoFiles }), null);
    assert.equal(attributionOf(entry, { repoRoot: repo }), null, "no evidence tables, no attribution");
    // A directory name is never evidence: the temp cwd basename matches nothing here and the repo name is irrelevant.
    assert.equal(attributionOf({ ...entry, targets: [], nestedHashes: [] }, { repoRoot: path.join(base, "cez"), repoFiles, chainHashes }), null);
    // Codex instructions-hash: the request-0 instructions block equals the repo's AGENTS.md.
    const agents = "# Agents\n\nUse pnpm.\n";
    const codex = fakeEntry("cx", { vendor: "codex", cwd: "/private/tmp/codex-copy", instructionHash: sha1(agents).slice(0, 16) });
    assert.deepEqual(attributionOf(codex, { repoRoot: repo, chainHashes: [sha1(agents)] }), { key, method: "instructions-hash", confidence: "exact" });
    assert.equal(attributionOf(codex, { repoRoot: repo, chainHashes: [sha1("other")] }), null);
    // Never for a repo cwd (the population rule owns those) and never for a harness run.
    assert.equal(attributionOf({ ...entry, cwd: "/Users/me/elsewhere", cwdKind: "repo" }, { repoRoot: repo, repoFiles, chainHashes }), null);
    assert.equal(attributionOf({ ...entry, kind: "harness" }, { repoRoot: repo, repoFiles, chainHashes }), null);

    // Population: the attributed temp copy joins the repo's roots and is not unattributed; a bare temp copy stays unattributed.
    const bare = fakeEntry("bare", { cwd: "/private/var/folders/zz/T/cez-root-lease-9", targets: ["a.ts", "b.ts"] });
    const inRepo = fakeEntry("r1", { cwd: repo });
    const pop = repoSessions({ entries: [entry, bare, inRepo], repoRoot: repo, projectKey: key, repoFiles, chainHashes });
    assert.deepEqual(pop.roots.map((e) => e.runId).sort(), ["claude:r1", entry.runId].sort());
    assert.equal(pop.attributionOf(entry).method, "nested-hash");
    assert.equal(pop.attributionOf(inRepo), null, "a cwd match carries no attribution record");
    assert.deepEqual(pop.unattributed.map((e) => e.runId), ["claude:bare"]);
    assert.equal(entryUnattributed(bare, { repoRoot: repo }), true);
    const overview = buildOverviewFromEntries([entry, bare, inRepo], { repoRoot: repo, projectKey: key, repoFiles, instructionFiles: inventory.files, now: NOW });
    assert.equal(overview.scope.sessions, 2);
    assert.equal(overview.scope.attributed, 1);
    assert.equal(overview.scope.unattributed, 1);
    assert.equal(overview.scope.harness, 0);
    const row = overview.runs.find((run) => run.id === entry.runId);
    assert.deepEqual(row.attribution, { key, method: "nested-hash", confidence: "exact" });
    assert.equal(overview.runs.find((run) => run.id === "claude:r1").attribution, undefined);
    assert.ok(!JSON.stringify(overview).includes(TEMP_COPY_CWD) && !JSON.stringify(overview).includes(base), "no absolute path in the overview");
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("harness runs: counted on the header, absent from repo and machine populations, habits, trends and offenders; listed only under kind=harness", async () => {
  const repo = "/Users/me/projects/alpha";
  const key = projectKeyFor(repo);
  const entries = [
    fakeEntry("r1", { cwd: repo }), fakeEntry("r2", { cwd: repo }), fakeEntry("r3", { cwd: repo }),
    fakeEntry("h1", { cwd: "/private/var/folders/ab/cez-root-isolation-1", entrypoint: "sdk-cli", requests: 1, toolCalls: 0 }),
    fakeEntry("h2", { cwd: "/private/var/folders/ab/cez-root-isolation-2", entrypoint: "sdk-cli", requests: 1, toolCalls: 0 }),
    fakeEntry("h3", { cwd: "/private/var/folders/ab/T/probe", entrypoint: "cli", requests: 0, toolCalls: 0 }),
    fakeEntry("sdk-in-repo", { cwd: repo, entrypoint: "sdk-cli", requests: 12, toolCalls: 5 }),
    fakeEntry("u1", { cwd: "/private/var/folders/ab/cez-root-lease-7", entrypoint: "cli", requests: 9, toolCalls: 4, targets: ["x.ts"] }),
  ];
  assert.deepEqual(entries.slice(3, 7).map((e) => e.kind), ["harness", "harness", "harness", "harness"]);
  assert.equal(entries[7].kind, "interactive");
  const pop = repoSessions({ entries, repoRoot: repo, projectKey: key });
  assert.deepEqual(pop.roots.map((e) => e.sessionId).sort(), ["r1", "r2", "r3"], "the SDK run in the repo's own cwd is a harness run too");
  assert.deepEqual(pop.harness.map((e) => e.sessionId).sort(), ["h1", "h2", "h3", "sdk-in-repo"]);
  assert.deepEqual(pop.unattributed.map((e) => e.sessionId), ["u1"], "only the temp session with real work and no evidence is unattributed");
  const machine = repoSessions({ entries });
  assert.equal(machine.roots.length, 4, "3 repo + u1 + nothing from the harness runs (the SDK run in the repo cwd included)");
  const listing = repoSessions({ entries, kind: "harness" });
  assert.deepEqual(listing.roots.map((e) => e.sessionId).sort(), ["h1", "h2", "h3", "sdk-in-repo"]);

  const overview = buildOverviewFromEntries(entries, { repoRoot: repo, projectKey: key, now: NOW });
  assert.equal(overview.scope.sessions, 3);
  assert.equal(overview.scope.machineSessions, 4);
  assert.equal(overview.scope.harness, 4);
  assert.equal(overview.scope.unattributed, 1);
  assert.equal(overview.scope.attributed, 0);
  assert.equal(overview.totals.runs, 3);
  assert.equal(overview.trends.sessions.reduce((a, b) => a + b, 0), 3);
  assert.ok(overview.runs.every((run) => run.kind === undefined));
  const all = buildOverviewFromEntries(entries, { repoRoot: repo, projectKey: key, scope: "all", now: NOW });
  assert.equal(all.totals.runs, 4, "scope=all never lists harness runs");
  assert.equal(all.scope.harness, 4);
  const harness = buildOverviewFromEntries(entries, { repoRoot: repo, projectKey: key, scope: "all", kind: "harness", now: NOW });
  assert.equal(harness.scope.kind, "harness");
  assert.deepEqual(harness.runs.map((run) => run.id).sort(), ["claude:h1", "claude:h2", "claude:h3", "claude:sdk-in-repo"]);
  assert.ok(harness.runs.every((run) => run.kind === "harness" && run.entrypoint));
  assert.equal(harness.totals.runs, 4);
  assert.equal(harness.scope.sessions, 3, "the repo line stays the repo's interactive sessions");

  // Habits: the fat read is in every record, but only the repo's population reaches the engine.
  const habits = await evaluateHabitsDetailed(pop.entries, { thresholds: { habitMinSessions: 3, habitFatTotalTokens: 30_000 }, rootOf: pop.rootOf });
  assert.equal(habits.sessions, 3);
  assert.equal(habits.findings.find((f) => f.ruleId === "H-01")?.sessions, 3);
  // The parsed harness fixture produces no habits evidence at all.
  const { run } = await (async () => ({ run: await parseClaudeSession(file(SESSIONS.harness), { home: HOME }) }))();
  const record = habitsOf(run, {});
  assert.deepEqual(record.fat, []);
  assert.deepEqual(record.fullReads, []);
});
