#!/usr/bin/env node
/**
 * Writes docs/sources.md from src/rules/sources.json: the knowledge base behind
 * every rule's "why it matters". Run after editing sources.json:
 *   node scripts/sources-doc.mjs            (writes ../../docs/sources.md)
 *   node scripts/sources-doc.mjs --check    (exit 1 when the doc is stale; used by the test suite)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(fs.readFileSync(path.join(here, "..", "src", "rules", "sources.json"), "utf8"));
const out = path.join(here, "..", "..", "..", "docs", "sources.md");
const rulesDir = path.join(here, "..", "src", "rules");

const titles = {};
for (const name of fs.readdirSync(rulesDir).filter((file) => /^[SBH]-\d{2}\.mjs$/.test(file))) {
  const text = fs.readFileSync(path.join(rulesDir, name), "utf8");
  titles[name.replace(".mjs", "")] = text.match(/title:\s*"([^"]+)"/)?.[1] ?? "";
}

export function render() {
  const byId = new Map(data.sources.map((source) => [source.id, source]));
  const ruleIds = Object.keys(data.rules).sort((a, b) => a[0].localeCompare(b[0]) || Number(a.slice(2)) - Number(b.slice(2)));
  const count = (basis) => ruleIds.filter((id) => data.rules[id].basis === basis).length;
  const lines = [
    "# Sources behind the rules",
    "",
    "<!-- Generated by packages/cli/scripts/sources-doc.mjs from packages/cli/src/rules/sources.json. Edit the JSON, then re-run the script. -->",
    "",
    "Every ContextScope rule carries a *why it matters*. This page lists what that rationale rests on, and says plainly where it rests on nothing but our judgement.",
    "",
    "- **sourced**: a cited source documents the mechanism the rule relies on.",
    "- **inferred**: the mechanism follows from cited sources, but no source states the rule itself.",
    "- **opinion**: a product judgement. Every numeric threshold (8k tokens, 4k handoff, 6k startup budget) is an opinion unless a source gives the number.",
    "",
    `${data.sources.length} sources · rules: ${count("sourced")} sourced, ${count("inferred")} inferred, ${count("opinion")} opinion · generated ${data.generatedAt ?? ""}`.trim(),
    "",
    "Precision on real repositories is measured separately, in [evaluation-findings.md](evaluation-findings.md).",
    "",
    "## Rules",
    "",
    "| Rule | Title | Basis | Sources | Note |",
    "|---|---|---|---|---|",
  ];
  for (const id of ruleIds) {
    const rule = data.rules[id];
    const refs = (rule.sources ?? []).map((sid) => byId.get(sid) ? `[${sid}](#${sid})` : sid).join(", ") || "—";
    const note = [rule.note, ...(rule.caveats ?? []).map((caveat) => `*Caveat:* ${caveat}`)].filter(Boolean).join(" ").replace(/\|/g, "\\|");
    lines.push(`| ${id} | ${titles[id] ?? ""} | ${rule.basis} | ${refs} | ${note} |`);
  }
  const groups = [["vendor-docs", "Vendor documentation"], ["standard", "Standards"], ["engineering-post", "Engineering posts"], ["paper", "Research papers"], ["practitioner", "Practitioner writing"]];
  lines.push("", "## Sources", "");
  for (const [type, heading] of groups) {
    const list = data.sources.filter((source) => source.type === type);
    if (!list.length) continue;
    lines.push(`### ${heading}`, "");
    for (const source of list) {
      const used = ruleIds.filter((id) => (data.rules[id].sources ?? []).includes(source.id));
      lines.push(`<a id="${source.id}"></a>`);
      lines.push(`- **[${source.title}](${source.url})**: ${[source.publisher, source.authors, source.year].filter(Boolean).join(", ")}${source.verified === "search-only" ? " *(verified by search only)*" : ""}`);
      if (source.summary) lines.push(`  ${source.summary}`);
      for (const point of source.keyPoints ?? []) lines.push(`  - ${point}`);
      if (used.length) lines.push(`  - Used by: ${used.join(", ")}`);
    }
    lines.push("");
  }
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const text = render();
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
    if (current !== text) { console.error("docs/sources.md is stale: run node packages/cli/scripts/sources-doc.mjs"); process.exit(1); }
  } else {
    fs.writeFileSync(out, text);
    console.log(`wrote ${path.relative(process.cwd(), out)} (${data.sources.length} sources, ${Object.keys(data.rules).length} rules)`);
  }
}
